### ISSUE TITLE
rdoc API documentation no longer available on rubydoc.info

### ISSUE THREAD

**Issue by garz75** [maxmind/GeoIP2-ruby#25]
The README.md of this GitHub project, the Spec file, and the https://dev.maxmind.com/geoip/geoip2/web-services/ page say that the API documentation is available at https://www.rubydoc.info/gems/maxmind-geoip2 but this page is a four-oh-four....

Thank you for your help.

**Comment by horgh** [comment]
Hi! Thank you for letting us know. I'm not sure why that is. I suspect there could be an indexing issue on rubydoc.info. I've posted on their forums asking for help, so we'll see what they say: https://rubydoc.tenderapp.com/discussions/problems/764-documentation-for-gems-missing?unresolve=true.

Until it's fixed, https://www.rubydoc.info/github/maxmind/GeoIP2-ruby/master may be useful. That renders from GitHub rather than from the gem, but it should be about the same.

**Comment by oschwald** [comment]
Thanks for reporting. It looks like RubyDoc.info has fixed their index and the link now works.
